---
- hosts: INPUTZONE
  remote_user: "{{ VML_DEPLOY_USER }}"
  tasks:
   - name: Permissions to base directory
     shell: chmod 777 *.sh
     args:
       chdir: "{{ BASE_DIR }}"
       warn: false

   - name: Permissions to deploy directory
     shell: chmod 777 *.sh
     args:
       chdir: "{{ VML_DEPLOY_DIR }}"
       warn: false

   - name: Execute start pnode in T node
     shell: "./vml_operations.sh {{ TNODE }} pnode Start"
     args:
       chdir: "{{ VML_DEPLOY_DIR }}"
     register: stopoutput
   - debug: var=stopoutput.stdout_lines

   - name: Listing Docker containers
     shell: docker ps
     register: containerlist
   - debug: var=containerlist.stdout_lines
